// Mocks generated by Mockito 5.4.6 from annotations
// in workout_tracker/test/features/exercise_master/exercise_master_notifier_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:workout_tracker/data/database/app_database.dart' as _i4;
import 'package:workout_tracker/data/repositories/exercise_master_repository.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [ExerciseMasterRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockExerciseMasterRepository extends _i1.Mock
    implements _i2.ExerciseMasterRepository {
  MockExerciseMasterRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.ExerciseMaster>> findAll() =>
      (super.noSuchMethod(
            Invocation.method(#findAll, []),
            returnValue: _i3.Future<List<_i4.ExerciseMaster>>.value(
              <_i4.ExerciseMaster>[],
            ),
          )
          as _i3.Future<List<_i4.ExerciseMaster>>);

  @override
  _i3.Future<int> insert(String? name, int? sortOrder) =>
      (super.noSuchMethod(
            Invocation.method(#insert, [name, sortOrder]),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<void> updateName(int? exerciseId, String? name) =>
      (super.noSuchMethod(
            Invocation.method(#updateName, [exerciseId, name]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> delete(int? exerciseId) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [exerciseId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateSortOrders(List<_i4.ExerciseMaster>? exercises) =>
      (super.noSuchMethod(
            Invocation.method(#updateSortOrders, [exercises]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
