// Mocks generated by Mockito 5.4.6 from annotations
// in workout_tracker/test/features/workout_list/workout_list_notifier_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:workout_tracker/data/database/app_database.dart' as _i4;
import 'package:workout_tracker/data/repositories/exercise_master_repository.dart'
    as _i6;
import 'package:workout_tracker/data/repositories/workout_session_repository.dart'
    as _i2;
import 'package:workout_tracker/data/repositories/workout_set_repository.dart'
    as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [WorkoutSessionRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockWorkoutSessionRepository extends _i1.Mock
    implements _i2.WorkoutSessionRepository {
  MockWorkoutSessionRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.WorkoutSession>> findAll() =>
      (super.noSuchMethod(
            Invocation.method(#findAll, []),
            returnValue: _i3.Future<List<_i4.WorkoutSession>>.value(
              <_i4.WorkoutSession>[],
            ),
          )
          as _i3.Future<List<_i4.WorkoutSession>>);

  @override
  _i3.Future<List<_i4.WorkoutSession>> findByFilter({
    DateTime? monthStart,
    DateTime? monthEnd,
    int? exerciseId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#findByFilter, [], {
              #monthStart: monthStart,
              #monthEnd: monthEnd,
              #exerciseId: exerciseId,
            }),
            returnValue: _i3.Future<List<_i4.WorkoutSession>>.value(
              <_i4.WorkoutSession>[],
            ),
          )
          as _i3.Future<List<_i4.WorkoutSession>>);

  @override
  _i3.Future<_i4.WorkoutSession?> findById(int? sessionId) =>
      (super.noSuchMethod(
            Invocation.method(#findById, [sessionId]),
            returnValue: _i3.Future<_i4.WorkoutSession?>.value(),
          )
          as _i3.Future<_i4.WorkoutSession?>);

  @override
  _i3.Future<int> insert({
    required DateTime? date,
    required int? focusLevel,
    String? memo,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#insert, [], {
              #date: date,
              #focusLevel: focusLevel,
              #memo: memo,
            }),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<void> update({
    required int? sessionId,
    required DateTime? date,
    required int? focusLevel,
    String? memo,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#update, [], {
              #sessionId: sessionId,
              #date: date,
              #focusLevel: focusLevel,
              #memo: memo,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> delete(int? sessionId) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [sessionId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [WorkoutSetRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockWorkoutSetRepository extends _i1.Mock
    implements _i5.WorkoutSetRepository {
  MockWorkoutSetRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.WorkoutSet>> findBySessionId(int? sessionId) =>
      (super.noSuchMethod(
            Invocation.method(#findBySessionId, [sessionId]),
            returnValue: _i3.Future<List<_i4.WorkoutSet>>.value(
              <_i4.WorkoutSet>[],
            ),
          )
          as _i3.Future<List<_i4.WorkoutSet>>);

  @override
  _i3.Future<void> insertAll(List<_i4.WorkoutSetsCompanion>? sets) =>
      (super.noSuchMethod(
            Invocation.method(#insertAll, [sets]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> replaceAll(
    int? sessionId,
    List<_i4.WorkoutSetsCompanion>? sets,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#replaceAll, [sessionId, sets]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteBySessionId(int? sessionId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteBySessionId, [sessionId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i4.WorkoutSet>> findAll() =>
      (super.noSuchMethod(
            Invocation.method(#findAll, []),
            returnValue: _i3.Future<List<_i4.WorkoutSet>>.value(
              <_i4.WorkoutSet>[],
            ),
          )
          as _i3.Future<List<_i4.WorkoutSet>>);
}

/// A class which mocks [ExerciseMasterRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockExerciseMasterRepository extends _i1.Mock
    implements _i6.ExerciseMasterRepository {
  MockExerciseMasterRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.ExerciseMaster>> findAll() =>
      (super.noSuchMethod(
            Invocation.method(#findAll, []),
            returnValue: _i3.Future<List<_i4.ExerciseMaster>>.value(
              <_i4.ExerciseMaster>[],
            ),
          )
          as _i3.Future<List<_i4.ExerciseMaster>>);

  @override
  _i3.Future<int> insert(String? name, int? sortOrder) =>
      (super.noSuchMethod(
            Invocation.method(#insert, [name, sortOrder]),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<void> updateName(int? exerciseId, String? name) =>
      (super.noSuchMethod(
            Invocation.method(#updateName, [exerciseId, name]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> delete(int? exerciseId) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [exerciseId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateSortOrders(List<_i4.ExerciseMaster>? exercises) =>
      (super.noSuchMethod(
            Invocation.method(#updateSortOrders, [exercises]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
